# The URL the site will be built for
base_url = "https://veeenu.github.io"

generate_feeds = true
compile_sass = true
minify_html = true
build_search_index = false
# extra_syntaxes_and_themes = ["syntaxes"]

[markdown]
highlight_code = true
highlight_theme = "one-dark"
render_emoji = true
external_link_target_blank = true
